#!/bin/bash

cd ./2-integrity;
perl MultipleComponentAssemblyMapping.pl --output 'run6.txt';
cd ../5-comparison;
perl CoordSystemAcrossSpecies.pl --output 'run6.txt';
cd ../2-integrity;
perl AssemblyMapping.pl --output 'run6.txt';
perl LRG.pl --output 'run6.txt';
perl SeqRegionCoordSystem.pl --output 'run6.txt';